channels:
dependencies:
  - jupyter
<<<<<<<< HEAD:tareas/20_giancarlo/pandas/environment.yml
  - pandas
  - pip
  - notebook
  - pip: # instalado con pip
    - seaborn
========
  - pip
  - pandas
  - notebook
  - pip: # instalado con pip
    - seaborn

>>>>>>>> upstream/main:tareas/95_Carlos/pandas/environment.yml
