channels:
  - conda-forge # canales de conda
  - anaconda # canales de conda
dependencies:
<<<<<<< HEAD
<<<<<<< HEAD
  - numpy
=======
  - numpy=1.21.0
>>>>>>> a019443 (Guardando localmente environment)
=======
  - numpy
>>>>>>> e18891d (quitanddo la versión específica de numpy)
  - pandas
  - pip
  - pip: # instalado con pip
    - seaborn