channels:
  - conda-forge # canales de conda
  - anaconda # canales de conda
dependencies:
<<<<<<<< HEAD:tareas/mariana48/virtual_envs/environment.yml
  - numpy=1.21.0
========
  - numpy
>>>>>>>> 2ff7102ab1608f0b2ad95775f6c12d3c52da69f9:tareas_v2/ALZ_19/numpy/environment.yml
  - pandas
  - pip
  - pip: # instalado con pip
    - seaborn