channels:
  - conda-forge # canales de conda
  - anaconda # canales de conda
dependencies:
  - numpy
  - pandas
  - pip
  - pip: # instalado con pip
<<<<<<< HEAD
    - seaborn
=======
    - seaborn
>>>>>>> 74434ff (Numpy enviroment)
